name: CI

on:
  push:
    branches:
      - 'developers/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.package }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - bowling-game/swift/bowling-game
          - game-of-life/swift/GameOfLife
          - interactions/swift/interactions
          - refactoring/swift/refactoring
          - string-calculator/swift/StringCalculator
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Swift version
        run: swift --version
      - name: Test
        working-directory: ${{ matrix.package }}
        run: swift test
